### ISSUE TITLE
heroku搭建完成后显示file not found

### ISSUE THREAD

**Issue by Ecalose** [tindy2013/heroku-subconverter#4]
我是通过底下那个模版链接直接部署的

**Comment by Ecalose** [comment]
已修改config内容，自己fork后修改配置后也显示同样问题

**Comment by shao222** [comment]
readme.md 里的url 地址改成你自己的仓库地址.

**Comment by Ecalose** [comment]
> readme.md 里的url 地址改成你自己的仓库地址.

模版地址也改了啊,然而还是8行，迷惑
